// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchAggregator.Models;

#nullable disable

namespace SearchAggregator.Migrations
{
    [DbContext(typeof(SearchContext))]
    [Migration("20230828132646_ChangedColumnDefaultValues")]
    partial class ChangedColumnDefaultValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchAggregator.Models.SearchAggregatorResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BingResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(MAX)")
                        .HasDefaultValue("[]");

                    b.Property<string>("GoogleResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(MAX)")
                        .HasDefaultValue("[]");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("YandexResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(MAX)")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.HasIndex("SearchText");

                    b.ToTable("SearchAggregatorResult", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
